allow anchors to be used for source and buildpack

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -11,6 +11,10 @@ echo() {
   /bin/echo "$1" "$2"
 }
 
+error() {
+  /bin/echo $*; exit 1
+}
+
 on_exit() {
   sleep 1
   printf "\000\042\000\001\\$(printf '%03o' $?)"
@@ -18,8 +22,13 @@ on_exit() {
 
 trap on_exit EXIT
 
-# finish the "Launching build slave..." line
-echo "done"
+if [ "$compile_dir" == "" ]; then
+  error "Aborting compilation"
+fi
+
+if [ ! -d $compile_dir ]; then
+  error "Aborting compilation"
+fi
 
 # get root dir
 root_dir=$(pwd)
@@ -31,6 +40,11 @@ mkdir -p $cache_dir
 
 # fetch buildpack
 cd $compile_dir
+BUILDPACK_ANCHOR=${BUILDPACK_URL#*#}
+BUILDPACK_URL=${BUILDPACK_URL%%#*}
+if [ "$BUILDPACK_ANCHOR" == "$BUILDPACK_URL" ]; then
+  BUILDPACK_ANCHOR=""
+fi
 echo -n "Fetching buildpack... "
 rm -rf .buildpack; mkdir -p .buildpack;
 case $BUILDPACK_URL in
@@ -44,8 +58,19 @@ case $BUILDPACK_URL in
     curl -s $BUILDPACK_URL -o- | tar xzf -
     cd ..
     ;;
+  *.git)
+    git clone --recursive $BUILDPACK_URL .buildpack >/dev/null 2>&1
+    if [ "$BUILDPACK_ANCHOR" != "" ]; then
+      cd .buildpack >/dev/null 2>&1
+      git remote update >/dev/null 2>&1
+      git checkout "$BUILDPACK_ANCHOR" >/dev/null 2>&1 || \
+        error "failed, no such ref: $BUILDPACK_ANCHOR"
+      cd - >/dev/null 2>&1
+    fi
+    ;;
   *)
-    git clone --depth 1 $BUILDPACK_URL .buildpack >/dev/null 2>&1
+    echo "failed"
+    error "Unknown buildpack type: $BUILDPACK_URL"
     ;;
 esac
 cd $compile_dir
diff --git a/bin/fetch b/bin/fetch
--- a/bin/fetch
+++ b/bin/fetch
@@ -11,7 +11,7 @@ echo() {
 }
 
 error() {
-  /bin/echo $*; exit 1
+  /bin/echo $* >&2; exit 1
 }
 
 # get root dir
@@ -22,21 +22,37 @@ compile_dir=$(mktemp -t compile_XXXXX)
 rm -rf $compile_dir
 mkdir -p $compile_dir
 
+source_anchor=${1#*#}
+source_url=${1%%#*}
+if [ "$source_anchor" == "$source_url" ]; then
+  source_anchor=""
+fi
+
+echo "done" >&2
+echo -n "Fetching app... " >&2
+
 # fetching app
-case $1 in
+case $source_url in
   *.json)
     manifest=$(mktemp -t manifest_XXXXX)
-    curl -s $1 -o $manifest
+    curl -s $source_url -o $manifest
     $root_dir/bin/download_manifest $manifest $compile_dir >/dev/null
     ;;
   *.git)
-    git clone "$1" "$compile_dir" --recursive --depth 1 >/dev/null 2>/dev/null
+    git clone "$source_url" "$compile_dir" --recursive >/dev/null 2>/dev/null
+    if [ "$source_anchor" != "" ]; then
+      cd $compile_dir >/dev/null 2>&1
+      git remote update >/dev/null 2>&1
+      git checkout "$source_anchor" >/dev/null 2>&1 || \
+        error "failed, no such ref: $source_anchor"
+      cd - >/dev/null 2>&1
+    fi
     ;;
   *)
-    error "Unknown source type: $1"
+    error "failed, unknown source type: $source_url"
     ;;
 esac
 
-manifest=$(mktemp -t manifest_XXXXX)
+echo "done" >&2
 
 echo $compile_dir
